name: Architecture Deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.10.2

      - name: Restore dependencies cache
        uses: actions/cache@v4
        id: cache-restore
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: architecture-dependencies

      - name: Build with Gradle
        working-directory: deploy/app
        run: gradle clean test distTar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: architecture-tar
          path: deploy/app/build/distributions/app.tar

      - name: Save dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: architecture-dependencies

  deploy-non-production:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: architecture-tar

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Deploy to Non Production
        run: |
          tar -xvf app.tar
          ./app/bin/app
        env:
          AZURE_SP_CLIENT_ID: ${{ secrets.AZURE_SP_CLIENT_ID }}
          AZURE_SP_CLIENT_SECRET: ${{ secrets.AZURE_SP_CLIENT_SECRET }}
          CI_CD_SERVICE_ACCOUNT_NAME: ${{ secrets.NON_PRODUCTION_CI_CD_SERVICE_ACCOUNT_NAME }}
          CI_CD_SERVICE_ACCOUNT_SECRET: ${{ secrets.NON_PRODUCTION_CI_CD_SERVICE_ACCOUNT_SECRET }}
          ENVIRONMENT: DEVELOPMENT

  deploy-production:
    needs: deploy-non-production
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: architecture-tar

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Deploy to Production
        run: |
          tar -xvf app.tar
          ./app/bin/app
        env:
          AZURE_SP_CLIENT_ID: ${{ secrets.AZURE_SP_CLIENT_ID }}
          AZURE_SP_CLIENT_SECRET: ${{ secrets.AZURE_SP_CLIENT_SECRET }}
          CI_CD_SERVICE_ACCOUNT_NAME: ${{ secrets.PRODUCTION_CI_CD_SERVICE_ACCOUNT_NAME }}
          CI_CD_SERVICE_ACCOUNT_SECRET: ${{ secrets.PRODUCTION_CI_CD_SERVICE_ACCOUNT_SECRET }}
          ENVIRONMENT: PRODUCTION
